name: Python Tests with Coverage

on:
  workflow_dispatch:

jobs:
  test:
    name: Run Unit Tests and Upload Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.x

      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Install ffmpeg via apt
        run: |
          sudo apt update
          sudo apt install ffmpeg -y

      - name: Create symbolic link for ffmpeg
        run: |
          sudo ln -s /usr/bin/ffmpeg /opt/homebrew/bin/ffmpeg


